version : '3.8'
networks:
  web:
    name: web
    external: true
  internal:
    driver: bridge
    
volumes:
  tachidesk_config:
    driver_opts:
      type: none
      device: /home/aimad/projects/manga-downloader/tachidesk/config
      o: bind
  tachidesk_downloads:
    driver_opts:
      type: none
      device: /media/storage/system/tachidesk_downloads
      o: bind
  komga_config:
    driver_opts:
      type: none
      device: /home/aimad/projects/manga-downloader/komga/config
      o: bind
  kavita_config:
    driver_opts:
      type: none
      device: /home/aimad/projects/manga-downloader/kavita/config
      o: bind
  
  mangas:
    driver_opts:
      type: none
      device: /media/storage/Medias/Mangas
      o: bind

services:
  tachidesk:
    image: ghcr.io/suwayomi/tachidesk
    container_name: tachidesk
    networks:
      - web
      - internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - LOGGING=file
    volumes:
      - tachidesk_config:/home/suwayomi/.local/share/Tachidesk
      - tachidesk_downloads:/home/suwayomi/.local/share/Tachidesk/downloads
    ports:
      - "4567:4567"
    restart: unless-stopped

  komga:
    image: gotson/komga
    container_name: komga
    networks:
      - web
    volumes:
      - komga_config:/config
      - mangas:/mangas
    ports:
      - "25600:25600"
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
  
  kavita:
    image: kizaing/kavita
    container_name: kavita
    networks:
      - web
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - mangas:/mangas
      - kavita_config:/kavita/config
    ports:
      - 5000:5000
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    
  downloader:
    image: manga-downloader:0.1.0-SNAPSHOT
    container_name: manga-downloader
    volumes:
      - mangas:/mangas
      - tachidesk_downloads:/tachidesk
    user: "1000:1000"
    networks:
      - internal
    environment:
      - "TACHIDESK_URL=http://tachidesk:4567"
      - "SOURCE_PATH=/tachidesk/downloads"
      - "DESTINATION_PATH=/mangas"
    restart: unless-stopped